schema_version: 1

context:
  name: pybammsolvers
  version: "0.8.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pybammsolvers-${{ version }}.tar.gz
  sha256: fb92fb785607df8ce3ad0d035c0bf61c418294f38f8c5fec82b18bff58c74042
  patches:
    # use conda-forge CasADi
    - 0001-Fix-USE_PYTHON_CASADI.patch
    # remove CXX11 ABI definition to avoid incompatibility
    - 0002-Remove-CXX11-ABI-Definition.patch
    # find BLAS but still set SUNDIALS_LIBRARIES for pybammsolvers
    - 0003-Fix-Windows-cmake-prefix-path.patch

build:
  number: 1
  script:
    # it is recommended to use the llvm-openmp package on windows
    # as vcomp14 is not updated by Microsoft anymore
    - if: win
      then: set "CXXFLAGS=%CXXFLAGS% /openmp:llvm"
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - scikit-build-core >=0.10
    - casadi
    - pybind11 >=3.0.1
    - pip
    - suitesparse
    # need sundials 7.6+ for openmp support on osx builds
    # remove once there is a migrator for sundials 7.7
    - sundials 7.7.*
    - if: not linux
      then: llvm-openmp
      else: libgomp
  run:
    - python
    - casadi
    - numpy

tests:
  - python:
      imports:
        - pybammsolvers
      pip_check: true

about:
  summary: Python interface for the IDAKLU solver
  homepage: https://github.com/pybamm-team/pybammsolvers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - prady0t
    - Saransh-cpp
    - agriyakhetarpal
